name: tournament-simulation

on:
    push:
        branches:
        - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  tournament:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Run tournament simulation
        run: python3 tournament.py
        env:
          PYTHONPATH: ${{ github.workspace }}:$PYTHONPATH

      - name: Remove previous leaderboard
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' '/## Leaderboard/,/^$/d' README.md
          else
            sed -i '/## Leaderboard/,/^$/d' README.md
          fi

      - name: Update leaderboard file
        run: |
          echo "## Leaderboard" > leadboard.md
          echo "| Rank | Team | Score |" >> leadboard.md
          echo "| --- | --- | --- |" >> leadboard.md
          cat results/lead_board.txt >> leadboard.md

      - name: Include leaderboard in README
        run: |
          awk 'NR==2{print "## Leaderboard\n"system("cat leadboard.md")}1' README.md > README.tmp && mv README.tmp README.md

      - name: Commit leaderboard changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update leaderboard results"
          add: "."
          default_author: github_actions